### ISSUE TITLE
Once Human

### ISSUE THREAD

**Issue by Asciicodeplus** [DKDave/Scripts#2]
the extraction fails for a lot of files, here's one example with file "res_normal_pack_2.npk":
---------------------------------------------------------------------------------------
  0d133d50 32820      vehicle\cruxiii\texture\cruxiii_interior_feature.256_mipmap.pvr
  066239f0 131124     character\player\female\face\face04\tex\face04_ssss.512_mipmap.pvr
  01c1ed80 9          character\cinematic\novice\novice05\door\novice05_door_skin.skeletonextra
Info:  algorithm   478
       offset      01c1ed80
       input size  0x00000009 9
       output size 0x00000009 9
       result      0xffffffb8 -72

Error: uncompressed data (-72) bigger than allocated buffer (9)
       It usually means that data is not compressed or uses another algorithm

Last script line before the error or that produced the error:
  30  CLog FILENAME OFFSET ZSIZE SIZE

- OFFSET       0x01c1ed80
- ZSIZE        0x00000009
- SIZE         0x00000009
  coverage file 0     0%   179508     301136920  . offset 01c1ed89

Press ENTER or close the window to quit
---------------------------------------------------------------------------------------

Found another script that extract all the files from the npk (see attached), it extracts the files compressed but they can be decompressed in the command line but it seems the names of the files extracted are not correct sometimes the pvr files contain mesh data and viceversa.

[CHnpkUnpacker.zip](https://github.com/DKDave/Scripts/files/13814951/CHnpkUnpacker.zip)

**Comment by DKDave** [comment]
The sample I had "res_normal_pack_1.npk" worked fine.  That other script is designed for older versions of the format, which is why it doesn't do the newer ZSTD compression.  I guess there are also some uncompressed files which haven't been accounted for, and also some files with size of 0.  I don't have a sample of that "pack_2" file to test though.  I'll have a look into it and update my script to account for other cases.

**Comment by DKDave** [comment]
I've updated my script, should work with uncompressed files as well.  If there are still issues with other archives, then let me know.  Thanks.

**Comment by Asciicodeplus** [comment]
it works great now, every one of the 130+ npks can be extracted, I found your py script for noesis to view the models and it crashes with some models but works for others, I understand that you are still working on that, I'll keep an eye on any updates regarding that, thx.
