### ISSUE TITLE
Yo-kai Watch 4 Noesis Script

### ISSUE THREAD

**Issue by Nathmrx2** [DKDave/Scripts#5]
Hello, I don't know if it's the correct place to contact you, but I justed wanted to know about the Yo-kai Watch 4 script you were creating, are you still working on it? Thank you in advance for your answer, it's just to know if I can still hope. (And I'm sorry if my English is bad)

**Comment by DKDave** [comment]
No, this isn't the correct place as I haven't published a fully working script yet.  I've still got some things to fix, but I don't know when it might be finished.
