### ISSUE TITLE
X reader 

### ISSUE THREAD

**Issue by berzerkaka** [DKDave/Scripts#7]
i have an xreader for noesis i just wan't help it's export fine with me the encryption file but the only issue it's export it without animation and same pose of the models not T pose any help ??

**Comment by DKDave** [comment]
I really have no idea what you mean.  What is x reader?  Which of my scripts?  Which game are you referring to?  My scripts don't do animations, so you won't get them, and the pose will be whatever the default of the character is in the file.

**Comment by berzerkaka** [comment]
x reader is for .x files it's for x heroes games
